title: Site Title
author: Site author
description: Site Description # required to build
github: [metadata]
repository: hippity-hipflask/hippity-hipflask.github.io
domain: hippity-hipflask.github.io
url: https://hippity-hipflask.github.io
baseurl: /
markdown: GFM
lsi: false
# safe: true
# incremental: true
timezone: Europe/Stockholm
# highlighter: rouge
sass:
  style: compact
